document.getElementById("h1_History").innerHTML="history of gurieli"
document.getElementById("history").innerHTML="Prince Mamia V Gurieli (1809-1826), last ruler of Guria principality in Western Georgia, took great interest in transforming and developing the agricultural sector Following the advice given by the French botanists Andre Michaux and his son Francois Andre Michaux, who were the first to bring the tea plant to the United States in 1799, the Prince ordered the first Tea - Camellia Sinensis samples. These were brought to his botanical garden by the Scotsman Jacob Montague Marr, together with other exotic plants. Cultivation of this once unknown plant has laid the grounds for the development of what in the following decades became one of the biggest agricultural industries in Georgia."

document.getElementById("h1_Brand").innerHTML="brand philsophy"
document.getElementById("brand").innerHTML="Following the advice given by the French botanists Andre Michaux and his son Francois Andre Michaux, who were the first to bring the tea plant to the United States in 1799, the Prince ordered the first Tea - Camellia Sinensis samples. These were brought to his botanical garden by the Scotsman Jacob Montague Marr, together with other exotic plants. "



//document.getElementById("AboutProduct").innerHTML="Professional tasters, sampling tea for the trade, taste but do not consume a light brew in which the liquor is separated from the leaf after five to six minutes. The appearance of both the dry and infused leaf is observed, and the aroma of vapour, colour of liquor, and creaming action (formation of solids when cooled) are assessed. Finally the liquor is taken into the mouth with a sucking noise, swirled around the tongue, brought into contact with the palate, cheek, and gums, and then drawn to the back of the mouth and up to the olfactory nerve in the nose before being expectorated. The liquor is thus felt, tasted, and smelled. Tasters have a large glossary of terms for the evaluation of tea, but the less-demanding consumer drinks it as a thirst quencher and stimulant and for its distinctive sour-harsh taste."
